#!/bin/bash

rm *.pyc \
   ./astra_test/injector.in ./astra_test/injector.Log.* ./astra_test/injector.*emit.??? \
   ./astra_test/*.log.??? ./astra_test/*.sol.* ./astra_test/SDPEN.out* ./astra_test/ALPSO_print.out* \
   ./astra_test/injector.????.??? ./astra_test/*.png \
   ./impact_test/fort.* ./impact_test/SDPEN.out* ./impact_test/ALPSO_print.out* ./impact_test/*.log.??? \
   ./impact_test/*.sol.* ./impact_test/*.png ./impact_test/ImpactT.in 2>/dev/null

rm -r .ipynb_checkpoints 2>/dev/null
